version: "3.5"

services:
  bot: 
    build: .
    container_name: bot
    command: python bot/main.py
    volumes:
      - ./:/app


  form: 
    build: .
    container_name: form
    command: uvicorn app_form.main:app --reload --host 10.0.0.5
    volumes:
      - ./:/app
