version: "3.5"

services:
  bot: 
    build:
      context: .
    container_name: bot
    command: python main.py
    volumes:
      - ./bot:/
    ports:
      - "8000:8000" 


  form: 
    build:  
      context: .
    container_name: app
    command: gunicorn -w 4 -b 0.0.0.0:8080 app_form.main:app 
    volumes:
      - ./app:/
    ports:
      - "8080:8080"
